// 20 dummy schools
export const schools = [
  {
    name: "Sunrise Public School",
    owner: "Rajesh Kumar",
    registerId: "SCH1001",
    email: "sunrise1@example.com",
    phone: "+919000000001",
    address: "123 MG Road",
    city: "Delhi",
    state: "Delhi",
  },
  {
    name: "Greenfield Academy",
    owner: "Anita Sharma",
    registerId: "SCH1002",
    email: "greenfield2@example.com",
    phone: "+919000000002",
    address: "45 Park Street",
    city: "Mumbai",
    state: "Maharashtra",
  },
  {
    name: "Bluebell High School",
    owner: "Vikram Singh",
    registerId: "SCH1003",
    email: "bluebell3@example.com",
    phone: "+919000000003",
    address: "67 Lakeview Avenue",
    city: "Bangalore",
    state: "Karnataka",
  },
  {
    name: "Horizon International",
    owner: "Sunita Mehra",
    registerId: "SCH1004",
    email: "horizon4@example.com",
    phone: "+919000000004",
    address: "89 Green Street",
    city: "Chennai",
    state: "Tamil Nadu",
  },
  {
    name: "Bright Future School",
    owner: "Rakesh Patel",
    registerId: "SCH1005",
    email: "bright5@example.com",
    phone: "+919000000005",
    address: "12 Lotus Lane",
    city: "Kolkata",
    state: "West Bengal",
  },
  {
    name: "Starlight Academy",
    owner: "Priya Desai",
    registerId: "SCH1006",
    email: "starlight6@example.com",
    phone: "+919000000006",
    address: "23 Rose Avenue",
    city: "Delhi",
    state: "Delhi",
  },
  {
    name: "Oakridge Public School",
    owner: "Amit Verma",
    registerId: "SCH1007",
    email: "oakridge7@example.com",
    phone: "+919000000007",
    address: "56 Maple Street",
    city: "Mumbai",
    state: "Maharashtra",
  },
  {
    name: "Riverdale High",
    owner: "Neha Kapoor",
    registerId: "SCH1008",
    email: "riverdale8@example.com",
    phone: "+919000000008",
    address: "78 River Road",
    city: "Bangalore",
    state: "Karnataka",
  },
  {
    name: "Crestwood Academy",
    owner: "Suresh Reddy",
    registerId: "SCH1009",
    email: "crestwood9@example.com",
    phone: "+919000000009",
    address: "90 Hilltop Drive",
    city: "Chennai",
    state: "Tamil Nadu",
  },
  {
    name: "Evergreen School",
    owner: "Anjali Rao",
    registerId: "SCH1010",
    email: "evergreen10@example.com",
    phone: "+919000000010",
    address: "34 Sunset Boulevard",
    city: "Kolkata",
    state: "West Bengal",
  },
//   {
//     name: "Sunshine International",
//     owner: "Rohit Malhotra",
//     registerId: "SCH1011",
//     email: "sunshine11@example.com",
//     phone: "+919000000011",
//     address: "21 Palm Street",
//     city: "Delhi",
//     state: "Delhi",
//   },
//   {
//     name: "Maple Leaf Academy",
//     owner: "Kavita Singh",
//     registerId: "SCH1012",
//     email: "maple12@example.com",
//     phone: "+919000000012",
//     address: "67 Oak Lane",
//     city: "Mumbai",
//     state: "Maharashtra",
//   },
//   {
//     name: "Pinecrest School",
//     owner: "Vijay Nair",
//     registerId: "SCH1013",
//     email: "pinecrest13@example.com",
//     phone: "+919000000013",
//     address: "89 Pine Street",
//     city: "Bangalore",
//     state: "Karnataka",
//   },
//   {
//     name: "Harmony High",
//     owner: "Sunil Joshi",
//     registerId: "SCH1014",
//     email: "harmony14@example.com",
//     phone: "+919000000014",
//     address: "12 Harmony Road",
//     city: "Chennai",
//     state: "Tamil Nadu",
//   },
//   {
//     name: "Bright Minds School",
//     owner: "Rekha Patel",
//     registerId: "SCH1015",
//     email: "brightminds15@example.com",
//     phone: "+919000000015",
//     address: "56 Wisdom Lane",
//     city: "Kolkata",
//     state: "West Bengal",
//   },
//   {
//     name: "Silver Oak Academy",
//     owner: "Manoj Kumar",
//     registerId: "SCH1016",
//     email: "silveroak16@example.com",
//     phone: "+919000000016",
//     address: "78 Silver Street",
//     city: "Delhi",
//     state: "Delhi",
//   },
//   {
//     name: "Cedar Grove School",
//     owner: "Nisha Sharma",
//     registerId: "SCH1017",
//     email: "cedargrove17@example.com",
//     phone: "+919000000017",
//     address: "90 Cedar Avenue",
//     city: "Mumbai",
//     state: "Maharashtra",
//   },
//   {
//     name: "Lakeview High",
//     owner: "Rajiv Kapoor",
//     registerId: "SCH1018",
//     email: "lakeview18@example.com",
//     phone: "+919000000018",
//     address: "23 Lake Road",
//     city: "Bangalore",
//     state: "Karnataka",
//   },
//   {
//     name: "Everest Academy",
//     owner: "Pooja Reddy",
//     registerId: "SCH1019",
//     email: "everest19@example.com",
//     phone: "+919000000019",
//     address: "45 Summit Street",
//     city: "Chennai",
//     state: "Tamil Nadu",
//   },
//   {
//     name: "Bright Horizon School",
//     owner: "Amitabh Sharma",
//     registerId: "SCH1020",
//     email: "brighthorizon20@example.com",
//     phone: "+919000000020",
//     address: "67 Horizon Lane",
//     city: "Kolkata",
//     state: "West Bengal",
//   },
];
